### PR TITLE
Enable discussions for handly

### PR DESCRIPTION
**Pull request by pisv**

### CODE REVIEW

**Review by netomi — APPROVED** [review]
LGTM, you can merge yourself by commenting with `/otterdog merge`

**Comment by netomi** [comment]
As a reminder: do not change settings via the web UI as that would make the configuration out of sync. Only change via updating the configuration. At some point in time, we will remove the sync check and just overwrite settings.

**Comment by pisv** [comment]
@netomi Thank you for your review and the reminder! 👍

**Pull request merged**
